version: '2'

services:

  mysql-server:
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
#      MYSQL_USER: myweb
#      MYSQL_PASSWORD: secret
    restart: always
    ports:
      - ${DATABASE_PORT}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    # networks:
    #   mysql_net:
     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}
    environment:
      PMA_HOST: mysql-server
      UPLOAD_LIMIT: 67108864
    # networks:
    #   mysql_net:
    
# networks:
#   mysql_net:
